# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

stlSort <- function(x) {
    .Call(`_rqPen_stlSort`, x)
}

findIndices <- function(x, k) {
    .Call(`_rqPen_findIndices`, x, k)
}

rqLossAug <- function(r, tau) {
    .Call(`_rqPen_rqLossAug`, r, tau)
}

rqHuberDerivAug <- function(r, tau, gamma) {
    .Call(`_rqPen_rqHuberDerivAug`, r, tau, gamma)
}

negGradientAug <- function(r, weights, tau, gamma, x, ntau) {
    .Call(`_rqPen_negGradientAug`, r, weights, tau, gamma, x, ntau)
}

weightedNorm <- function(x, normweights) {
    .Call(`_rqPen_weightedNorm`, x, normweights)
}

solvebetaCpp <- function(x, y, n, tau, gamma, weights, groupIndex, lambdaj, wlambda, wtau, eigenval, betaini, maxIter, epsilon, ntau) {
    .Call(`_rqPen_solvebetaCpp`, x, y, n, tau, gamma, weights, groupIndex, lambdaj, wlambda, wtau, eigenval, betaini, maxIter, epsilon, ntau)
}

