# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

neg_gradient_aug <- function(r, weights, tau, gamma, x, ntau) {
    .Call(`_rqPen_neg_gradient_aug`, r, weights, tau, gamma, x, ntau)
}

weighted_norm <- function(x, normweights) {
    .Call(`_rqPen_weighted_norm`, x, normweights)
}

solvebetaCpp <- function(x, y, n, tau, gamma, weights, groupIndex, lambdaj, wlambda, wtau, eigenval, betaini, maxIter, epsilon, ntau) {
    .Call(`_rqPen_solvebetaCpp`, x, y, n, tau, gamma, weights, groupIndex, lambdaj, wlambda, wtau, eigenval, betaini, maxIter, epsilon, ntau)
}

